// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOcezTxHko-4rUcmuDy8u91Ky8yOUWX4g',
    appId: '1:1009772294409:web:02540235b4085889d223d8',
    messagingSenderId: '1009772294409',
    projectId: 'agri-leafy',
    authDomain: 'agri-leafy.firebaseapp.com',
    storageBucket: 'agri-leafy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK-NMPIHMLSyigaC0nZ_heGH_6z397Pgc',
    appId: '1:1009772294409:android:e8ed1fbd71b29382d223d8',
    messagingSenderId: '1009772294409',
    projectId: 'agri-leafy',
    storageBucket: 'agri-leafy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo5USlING-fuLYURPOMRUwqwJAVQbauJI',
    appId: '1:1009772294409:ios:dd0984b4948d2f03d223d8',
    messagingSenderId: '1009772294409',
    projectId: 'agri-leafy',
    storageBucket: 'agri-leafy.firebasestorage.app',
    iosBundleId: 'com.example.capstone2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo5USlING-fuLYURPOMRUwqwJAVQbauJI',
    appId: '1:1009772294409:ios:dd0984b4948d2f03d223d8',
    messagingSenderId: '1009772294409',
    projectId: 'agri-leafy',
    storageBucket: 'agri-leafy.firebasestorage.app',
    iosBundleId: 'com.example.capstone2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOcezTxHko-4rUcmuDy8u91Ky8yOUWX4g',
    appId: '1:1009772294409:web:10bda68cd987e247d223d8',
    messagingSenderId: '1009772294409',
    projectId: 'agri-leafy',
    authDomain: 'agri-leafy.firebaseapp.com',
    storageBucket: 'agri-leafy.firebasestorage.app',
  );
}
